---
title: "Comparing HOBO DO loggers: beginning of the season post-calibration comparison in the Lab"
author: "Cyndy Desjardins"
date: "12/05/2022"
output: 
  html_document:
    keep_md: true
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, packages, include=FALSE}
library(data.table)
library(tidyverse)
library(janitor)
library(here)
library(broom)
library(lubridate) 
library(fs)

```

```{r, loading data, include=FALSE}
#### I've made this rmd file so that the default when you knit the file  is to run ALL the files in the raw_data folder. I've broken the analyses down by season, and then all of the seasons together. If you don't want any of these chunks to be included in the final HTML change the echo=FALSE to include=FALSE at the top of each chunk you want excluded. If you DO want them included in the final HTML doc, then just make sure it says echo=FALSE at the top of the chunk. 

LC_root <- tibble(files = fs::dir_ls(here("HOBO_DO_loggers", "raw_data"))) %>%  # create a tibble of files in the raw data folder
  mutate(data = pmap(list(files), 
                     ~ read_csv(..1, skip = 2, col_names = c("sample_numb", "date", "time", "do_conc_mg_l", "temp_c"))[1:5])) %>%  # loading each individual file as a tibble-within-a-tibble (skipping the first 2 rows as we don't need the serial number just yet and we want to make our own col names)
  mutate(data = pmap(list(files, data), 
                     ~ mutate(..2, source_file = as.character(..1)))) %>% # keeping the source files for each individual dataset so that we can extract the serial number below
  select(data) %>% # select only the actual data tibbles
  map_df(bind_rows) %>%  # bind them all into one tibble
  mutate(loggerID = stringr::str_extract(source_file, "[:digit:]{8}")) %>% # extract the logger serial number using regex
  select(-source_file) %>% # we don't need the source_file anymore now that we've extracted the serial number
  mutate(date = mdy(date),
         month = month(date)) %>% 
  mutate(season = ifelse(month==5|month==6, "spring", ifelse(month==7|month==8, "summer", "fall"))) 

```



### Spring data plots
##### I trimmed the data, using only the data up until timepoint 276

```{r, SPRING data analysis, echo=FALSE, warning=FALSE}
LC_spring <- LC_root %>% 
  filter(season == "spring", 
         sample_numb<277) ###*** THIS LAST LINE WILL NEED TO BE CHANGED BASED ON WHEN THE LOGGERS WERE IN AND OUT OF THE WATER: THAT IS YOU'LL WANT TO USE THIS LINE OF CODE TO TRIM THE DATA TO WHAT YOU WANT IT TO BE ACTUALLY COMPARING!!!***

  
LC_spring %>% 
  ggplot() + 
  geom_point(aes(x = sample_numb, 
                 y = do_conc_mg_l, 
                 colour = loggerID)) +
  labs(x = " Sample number as a proxy of time", 
       y = "DO concentration (mg/L)")

LC_spring %>% 
  ggplot() +
  geom_boxplot(aes(x = loggerID, 
                   y = do_conc_mg_l)) +
  theme_classic() +
  theme(axis.text = element_text(angle = 90)) +
  labs(x = "Logger Serial Number", 
       y = "DO Concentration (mg/L)")
```


##### Summer data plots

```{r, SUMMER data and analysis, include=FALSE, warning=FALSE}
LC_summer <- LC_root %>% 
  filter(season == "summer", 
         sample_numb<110) ###*** THIS LAST LINE WILL NEED TO BE CHANGED BASED ON WHEN THE LOGGERS WERE IN AND OUT OF THE WATER: THAT IS YOU'LL WANT TO USE THIS LINE OF CODE TO TRIM THE DATA TO WHAT YOU WANT IT TO BE ACTUALLY COMPARING!!!***

  
LC_summer %>% 
  ggplot() + 
  geom_point(aes(x = sample_numb, 
                 y = do_conc_mg_l, 
                 colour = loggerID)) +
  labs(x = " Sample number as a proxy of time", 
       y = "DO concentration (mg/L)")

LC_summer %>% 
  ggplot() +
  geom_boxplot(aes(x = loggerID, 
                   y = do_conc_mg_l)) +
  theme_classic() +
  theme(axis.text = element_text(angle = 90)) +
  labs(x = "Logger Serial Number", 
       y = "DO Concentration (mg/L)")
```



##### Fall data plots

```{r, FALL data and analysis, include=FALSE, warning=FALSE}
LC_fall <- LC_root %>% 
  filter(season == "fall", 
         sample_numb<550) ###*** THIS LAST LINE WILL NEED TO BE CHANGED BASED ON WHEN THE LOGGERS WERE IN AND OUT OF THE WATER: THAT IS YOU'LL WANT TO USE THIS LINE OF CODE TO TRIM THE DATA TO WHAT YOU WANT IT TO BE ACTUALLY COMPARING!!!***

  
LC_fall %>% 
  ggplot() + 
  geom_point(aes(x = sample_numb, 
                 y = do_conc_mg_l, 
                 colour = loggerID)) +
  labs(x = " Sample number as a proxy of time", 
       y = "DO concentration (mg/L)")

LC_fall %>% 
  ggplot() +
  geom_boxplot(aes(x = loggerID, 
                   y = do_conc_mg_l)) +
  theme_classic() +
  theme(axis.text = element_text(angle = 90)) +
  labs(x = "Logger Serial Number", 
       y = "DO Concentration (mg/L)")

```


##### All seasons data plots

```{r, comparing the seasons, include=FALSE, warning=FALSE}
LC_allplot <- LC_root %>% 
  filter(sample_numb<110) %>% 
  ggplot() +
  facet_grid(~season) +
  geom_point(aes(x = sample_numb, 
                 y = do_conc_mg_l,
                 colour = loggerID)) +
  labs(x = " Sample number as a proxy of time", 
       y = "DO concentration (mg/L)")
print(LC_allplot)
```


