---
title: "Comparing HOBO DO loggers vs PME MiniDOt loggers: beginning of the season deployed for ~24hrs in L239"
author: "Cyndy Desjardins"
date: '2022-06-21'
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, packages, include=FALSE}
library(data.table)
library(tidyverse)
library(janitor)
library(here)
library(broom)
library(lubridate) 
library(fs)

```

```{r, loading HOBO data, include=FALSE}

HOBO_data <- tibble(files = fs::dir_ls(here("Comparing_HOBO_vs_MiniDOts", "raw_data", "HOBO"))) %>%  # create a tibble of files in the raw data folder
  mutate(HOBO_data = pmap(list(files), 
                     ~ read_csv(..1, skip = 2, col_names = c("sample_numb", "date", "time", "do_conc_mg_l", "temp_c"))[1:5])) %>%  # loading each individual file as a tibble-within-a-tibble (skipping the first 2 rows as we don't need the serial number just yet and we want to make our own col names)
  mutate(HOBO_data = pmap(list(files, HOBO_data), 
                     ~ mutate(..2, source_file = as.character(..1)))) %>% # keeping the source files for each individual dataset so that we can extract the serial number below
  select(HOBO_data) %>% # select only the actual data tibbles
  map_df(bind_rows) %>%  # bind them all into one tibble
  mutate(loggerID = stringr::str_extract(source_file, "[:digit:]{8}")) %>% # extract the logger serial number using regex
  select(-source_file) %>% # we don't need the source_file anymore now that we've extracted the serial number
  mutate(date = mdy(date),
         logger_type = "HOBO") %>% 
  filter(sample_numb<188, 
         sample_numb>25)


```
You can see from the two plots below that LoggerID#1092224 strayed from the bunch towards the end of the deployment... I'm not really sure why that would be. This logger has been deployed in 114 (CHECK ON THIS!) AS CAT MAY BE USING IT ON THE BENTHIC DOMES.

```{r, Cleaning up HOBO Data, echo=FALSE, warning=FALSE}
HOBO_plot <- HOBO_data %>% 
  filter(sample_numb<188, 
         sample_numb>25) ### THIS LAST LINE WILL NEED TO BE CHANGED BASED ON WHEN THE LOGGERS WERE IN AND OUT OF THE WATER: THAT IS YOU'LL WANT TO USE THIS LINE OF CODE TO TRIM THE DATA TO WHAT YOU WANT IT TO BE ACTUALLY COMPARING!!!

  
HOBO_plot %>% 
  ggplot() + 
  geom_point(aes(x = sample_numb, 
                 y = do_conc_mg_l, 
                 colour = loggerID)) +
  labs(x = " Sample number as a proxy of time", 
       y = "DO concentration (mg/L)")

HOBO_plot %>% 
  ggplot() +
  geom_boxplot(aes(x = loggerID, 
                   y = do_conc_mg_l)) +
  theme_classic() +
  theme(axis.text = element_text(angle = 90)) +
  labs(x = "Logger Serial Number", 
       y = "DO Concentration (mg/L)")
```







```{r, loading miniDOt data, include=FALSE}
data_dir <- here("Comparing_HOBO_vs_MiniDOts", "raw_data", "MiniDOts")

miniDOt_data <- tibble(files = fs::dir_ls(data_dir, recurse = TRUE)) %>% # creates a tibble with all the files in the listed folder
  mutate(files = as.character(files)) %>% 
  filter(str_detect(files, "txt$")) %>% 
  mutate(miniDOt_data = purrr::pmap(list(files), ~ read_delim(..1, delim = "," , skip = 2, col_names = TRUE))) %>%  # We load each individual file as a tibble-within-a-tibble
  mutate(miniDOt_data = purrr::pmap(list(files, miniDOt_data), ~ mutate(..2, source_file = as.character(..1)))) %>% # To each individual dataset we add the name of the file it came from (for reference)
  select(miniDOt_data) %>% # select only the actual data tibbles
  purrr::map_df(bind_rows) %>%  # bind them all into one tibble
  janitor::clean_names()

miniDOt_data <- miniDOt_data %>% 
  mutate(tibble(path_elements = str_split(miniDOt_data$source_file, "/"))) %>% 
  mutate(elements_subset = pmap(list(path_elements),
       ~tibble(source = tail(..1, 2)))) %>% 
  mutate(serial_number = pmap_chr(list(elements_subset),
                                  ~..1[[1,1]]),
         file_date = pmap_chr(list(elements_subset),
                                  ~..1[[2,1]])) %>% 
  select(-elements_subset, - path_elements, - source_file) %>% 
  mutate(file_date = str_remove(file_date, "Z.txt")) %>% 
  mutate(file_date = ymd_hms(file_date)) %>%
  mutate(serial_number = str_remove(serial_number, "7450-")) %>% 
  select(serial_number, file_date, everything()) %>% 
  mutate(logger_type = "MiniDOt") %>% 
  select(-time_sec, -bv_volts, -q)
  
miniDOt_data$sample_numb <- 1:nrow(miniDOt_data)

colnames(miniDOt_data) <- c("loggerID", "date_time", "temp_c", "do_conc_mg_l", "logger_type", "sample_numb")

miniDOt_data <- miniDOt_data %>% 
  mutate(date = as_date(date_time), 
         time = format(date_time, format="%H:%M:%S")) %>% 
  select(-date_time) 

miniDOt_data$do_conc_mg_l <- as.numeric(miniDOt_data$do_conc_mg_l)
miniDOt_data$sample_numb <- as.numeric(miniDOt_data$sample_numb)

#### NEED TO FIX TIME COLUMNS TO MATCH DATA TYPES THEN NEED TO MERGE DFs!!!!!



```