---
title: "Comparing PME miniDOts in the lab"
author: "Cyndy Desjardins"
date: '2022-06-02'
output: html_document:
          keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, packages, include=FALSE}
library(data.table)
library(tidyverse)
library(janitor)
library(here)
library(broom)
library(lubridate) 
library(fs)

```

```{r, loading data, include = FALSE}
LC_root <- tibble(files = fs::dir_ls(here("PME_miniDOts", "raw_data"))) %>% 
  mutate(data = pmap(list(files), 
                     ~ read_csv(..1, skip = 3, col_names = c("sample_numb", "volts", "temp_c", "do_conc_mg_l", 
                                                              "Q"))[1:5])) %>% 
  mutate(data = pmap(list(files, data), 
                     ~ mutate(..2, source_file = as.character(..1)))) %>% # keeping the source files for each individual dataset so that we can extract the serial number below
  select(data) %>% # select only the actual data tibbles
  map_df(bind_rows) %>%  # bind them all into one tibble
  mutate(loggerID = stringr::str_extract(source_file, "[:digit:]{6}")) %>% # extract the logger serial number using regex
  select(-source_file)
```


```{r, plotting all data, include = FALSE}
LC_allpoint <- LC_root %>% 
  filter(sample_numb<1652275000,
         sample_numb>1652220000) %>% 
  ggplot() +
  geom_point(aes(x = sample_numb, 
                 y = do_conc_mg_l,
                 colour = loggerID)) +
  labs(x = " Sample number as a proxy of time", 
       y = "DO concentration (mg/L)")
print(LC_allpoint)

LC_allbox <- LC_root %>% 
    filter(sample_numb<1652275000,
           sample_numb>1652220000) %>% 
  ggplot() +
  geom_boxplot(aes(x = loggerID, 
                   y = do_conc_mg_l)) +
  theme_classic() +
  theme(axis.text = element_text(angle = 90)) +
  labs(x = "Logger Serial Number", 
       y = "DO Concentration (mg/L)")
print(LC_allbox)
```

